-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  role text default 'user',
  points integer default 0
);

-- Drivers table
create table drivers (
  id bigint generated by default as identity primary key,
  name text not null,
  team text not null,
  code text
);

-- Races table (2026 Calendar)
create table races (
  id bigint generated by default as identity primary key,
  name text not null,
  date timestamp with time zone not null,
  track text not null,
  status text default 'scheduled', -- scheduled, open, closed, finished
  variable_driver_id bigint references drivers(id),
  is_test_race boolean default false
);

-- Bets table
create table bets (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  race_id bigint references races(id) not null,
  pole_driver_id bigint references drivers(id),
  p1_driver_id bigint references drivers(id),
  p2_driver_id bigint references drivers(id),
  p3_driver_id bigint references drivers(id),
  p4_driver_id bigint references drivers(id),
  p5_driver_id bigint references drivers(id),
  bortoleto_pos integer, -- 1-20 or maybe higher numbers for DNF codes if we want
  variable_driver_pos integer,
  catapulta boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, race_id)
);

-- Enable RLS
alter table profiles enable row level security;
alter table drivers enable row level security;
alter table races enable row level security;
alter table bets enable row level security;

-- Policies
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

create policy "Drivers are viewable by everyone." on drivers for select using (true);
create policy "Races are viewable by everyone." on races for select using (true);

create policy "Users can view their own bets." on bets for select using (auth.uid() = user_id);
create policy "Users can create bets." on bets for insert with check (auth.uid() = user_id);
create policy "Users can update their own bets." on bets for update using (auth.uid() = user_id);

-- Admin policies (assuming role='admin' in profiles for admin users)
-- For simplicity, let's keep it defined but commented out or basic for now.
-- In a real app we'd need a function to check role.
